-- Enable pgvector extension for vector storage
create extension if not exists vector;

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade, -- Link to articles table
  content text,                           -- Text content (LangChain expects 'content' field)
  metadata jsonb,                         -- Metadata (e.g., source, author, etc.)
  embedding vector(1536),                 -- 1536-dimensional vector (compatible with text-embedding-3-small)
  created_at timestamptz default now()
);

-- Create HNSW index on vector field for fast similarity search
create index on public.document_chunks using hnsw (embedding vector_cosine_ops);