-- Run this in your Supabase SQL Editor

create table public.articles (
  id bigint generated by default as identity primary key,
  hn_id integer unique not null,          -- Original HN ID
  original_title text not null,           -- Original English title
  original_url text,                      -- Original URL (may be null for Ask HN)
  score integer,                          -- HN score
  posted_at timestamptz,                  -- Posted time
  raw_content text,                       -- Crawled webpage content or HN text (for RAG)
  translated_title text,                  -- Translated Chinese title
  summary text,                           -- One sentence summary
  detailed_analysis jsonb,                -- Structured analysis (JSON)
  created_at timestamptz default now()
);

-- These indexes are for accelerating queries or ordering by score or posted_at only
create index articles_score_idx on public.articles (score desc);
create index articles_posted_at_idx on public.articles (posted_at desc);

