-- Run this in your Supabase SQL Editor

create table public.articles (
  id bigint generated by default as identity primary key,
  hn_id integer unique not null,          -- Original HN ID
  type text,                              -- Type (story, job, etc.)
  by text,                                -- Author username
  original_title text not null,           -- Original English title
  original_url text,                      -- Original URL (may be null for Ask HN)
  score integer,                          -- HN score
  posted_at timestamptz,                  -- Posted time
  
  kids integer[],                         -- Array of comment IDs
  parent integer,                         -- Parent ID (if applicable)
  
  raw_content text,                       -- Crawled webpage content or HN text (for RAG)
  image_urls text[],                      -- Array of image URLs from the article
  
  translated_title text,                  -- Translated Chinese title
  summary text,                           -- One sentence summary
  detailed_analysis jsonb,                -- Structured analysis (JSON)
  comment_analysis jsonb,                 -- Comment analysis (JSON)
  
  created_at timestamptz default now()
);

-- Indexes for performance
create index articles_score_idx on public.articles (score desc);
create index articles_posted_at_idx on public.articles (posted_at desc);
create index articles_hn_id_idx on public.articles (hn_id);
